# Generated by Django 4.1.3 on 2022-12-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_blocked_user_location_alter_user_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Блокировка пользователя'),
        ),
    ]
