# Generated by Django 4.1.3 on 2022-12-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, default='default_media/users/logo/logo.jpg', null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
