# Generated by Django 4.1.3 on 2022-12-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='users/logo/logo.jpg', upload_to='', verbose_name='Аватар'),
        ),
    ]
