# Generated by Django 4.1.3 on 2022-12-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название компании')),
                ('category', models.CharField(choices=[('it', 'IT'), ('catering', 'Catering')], max_length=50, verbose_name='Категория компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание компании')),
                ('location', models.CharField(max_length=50, verbose_name='Местонахождение')),
                ('site', models.URLField(blank=True, null=True, unique=True, verbose_name='Сайт компании')),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
