# Generated by Django 4.1.3 on 2022-12-09 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_company_logo_company_recruiters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='recruiters',
        ),
        migrations.AddField(
            model_name='company',
            name='recruiters',
            field=models.ManyToManyField(blank=True, null=True, related_name='recruiters', to=settings.AUTH_USER_MODEL, verbose_name='recruiters'),
        ),
    ]
