# Generated by Django 4.1.3 on 2022-12-10 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_alter_company_recruiters'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_of_the_company', to=settings.AUTH_USER_MODEL, verbose_name='Создатель компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Блокировка компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='recruiters',
            field=models.ManyToManyField(related_name='recruiter_in', to=settings.AUTH_USER_MODEL, verbose_name='Рекрутеры компании'),
        ),
    ]
